# Generated by Django 5.0.4 on 2024-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_image_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image2",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
    ]
