# Generated by Django 5.0.4 on 2024-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_show_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
